# Generated by Django 5.2.15 on 2026-06-08 20:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('titulo_original', models.CharField(blank=True, max_length=180)),
                ('ano_lancamento', models.PositiveIntegerField(blank=True, null=True)),
                ('diretor', models.CharField(blank=True, max_length=120)),
                ('genero', models.CharField(db_index=True, max_length=80)),
                ('duracao_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('sinopse', models.TextField(blank=True)),
                ('poster', models.URLField(blank=True)),
                ('total_visualizacoes', models.PositiveIntegerField(default=0)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='FilmeVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado_em', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='filmes.filme')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualização de filme',
                'verbose_name_plural': 'Visualizações de filmes',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoFilme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='filmes.filme')),
            ],
            options={
                'verbose_name': 'Avaliação de filme',
                'verbose_name_plural': 'Avaliações de filmes',
                'unique_together': {('usuario', 'filme')},
            },
        ),
        migrations.CreateModel(
            name='FilmeFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='filmes.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filme favorito',
                'verbose_name_plural': 'Filmes favoritos',
                'unique_together': {('usuario', 'filme')},
            },
        ),
    ]
